// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternation_text: dynamic(() => import("./AlternatingText")),
  bigtext: dynamic(() => import("./Bigtext")),
  carousel: dynamic(() => import("./Carousel")),
  hero: dynamic(() => import("./Hero")),
  sky_dive: dynamic(() => import("./SkyDive")),
};
